### ISSUE TITLE
Will Quicksql support PostgreSQL?

### ISSUE THREAD

**Issue by wucangeo** [Qihoo360/Quicksql#66]
PostgreSQL is better than MySQL with a lot of extensions. 
Will Quicksql support PostgreSQL?
Thanks.

**Comment by Functor10** [comment]
wucangeo, thanks for your suggestion. 
Since there is no corresponding usage scenario within the company, we will not consider connecting PostgreSQL in the short term.
But we are working on building an interface that can be customized by developers, and finally developers can connect the new data source by itself.

**Comment by wucangeo** [comment]
> wucangeo, thanks for your suggestion.
> Since there is no corresponding usage scenario within the company, we will not consider connecting PostgreSQL in the short term.
> But we are working on building an interface that can be customized by developers, and finally developers can connect the new data source by itself.

It's also a good news, thanks for reply. 
Hope we can do it by myself soon.
